### ISSUE TITLE
Unable to build graph

### ISSUE THREAD

**Issue by sidevshiy** [maize-genetics/rPHG2#8]
Hello,

I was trying to use rPHG2. But I am getting an error. Could you please help me ?

> hVcfFiles <- system.file(
+     "extdata", 
+     c("LineA.h.vcf", "LineB.h.vcf"), 
+     package = "rPHG2"
+ )
> localCon <- hVcfFiles |> PHGLocalCon()
> 
> localCon
A PHGLocalCon connection object
 ❯ DB URI....   : ◯
 ❯ hVCF Files...: ◉
> graph <- localCon |> buildHaplotypeGraph()
Error in hapGraphConstructor(hVcfFiles(phgLocalCon)) : 
  java.lang.ClassNotFoundException
  
  
  Java version is 21.0.3
  
  > java_version <- .jcall("java/lang/System", "S", "getProperty", "java.version")
> print(paste("Java version:", java_version))
[1] "Java version: 21.0.3"

**Comment by btmonier** [comment]
Hi Evgenii,

Thanks for checking out our early builds. Before building the graph, did you initialize the JAR files found in the PHGv2 release? For example:

``` r
phgPath <- "dir_containing_phgv2tar/phg/lib/"

initPhg(phgPath)
```

This will (1) initialize the JVM for your R session and (2) add the PHGv2 Kotlin classes to class path.

Apologies for not making this clear yet in the documentation since we are still optimizing the workflows.

**Comment by sidevshiy** [comment]
Thank you! That was a problem. 
Could you give an advise how to construct graph phgDs from "Filter Data" section ?
Do you have any functionality to show SNPs from specific region or something in rPHG ?

**Comment by btmonier** [comment]
The `graph` object made from `buildHaplotypeGraph()` is used to build the Kotlin PHG graph in the JVM and creates a simple (yet abstract) data object that links the R side to the Kotlin side's graph:

``` r
graph <- phgLocalCon |> buildHaplotypeGraph()
```

Once you have your `graph` object, you can evaluate this into "100% R Space" (e.g., `data.frame` objects, vectors, `list`s, etc.) using [`readPhgDataSet()`](https://rphg2.maizegenetics.net/reference/readPhgDataSet.html):

``` r
phgDataSet <- graph |> readPhgDataSet()
```

This new R object can be used to filter based on samples/taxa using `filterSamples()` **or** on regions of interest via `filterRefRanges()`. For example let's say you have SNPs of interest on chromosome 3 (e.g., `chr03`) and they are found within the start/stop sites of `100` and `50000` base pairs. You could filter your data set to the reference ranges that are found within this region by first constructing a `GRanges` object and passing to the `filterRefRanges()` site:

``` r
gr <- GRanges(
    seqnames = "chr03",
    ranges = IRanges(
        c(100, 50000)
    )
)


phgSub <- phgDataSet |> filterRefRanges(gr)
```

This will return a filtered set including all of the reference ranges that fall within that range and the haplotype IDs and their respective regions in the assemblies using the `read*` family of functions.
